### ISSUE TITLE
Add omitempty JSON tag to lex.Entry (lex/entry.go) fields

### ISSUE THREAD

**Issue by NikolajLindberg** [stts-se/pronlex#31]
For nicer printing of lexicon entry JSON,  add ",omitempty" to the JSON directive on all optional fields

**Comment by HannaLindgren** [comment]
I have done the easy part of this task.

In order to do this completely for embedded structs such as LexRef, Lemma and EntryStatus, we need to use pointers (e.g. Entry should have a *LexRef instead of LexRef). That requires some more work so I won't do that right now.

Some info: https://www.sohamkamani.com/blog/golang/2018-07-19-golang-omitempty/

**Comment by HannaLindgren** [comment]
Closing, since it's fixed as much as possible for now.
